# Generated by Django 5.2.8 on 2025-11-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55)),
                ("service", models.CharField(max_length=55)),
                ("date", models.DateField(default="10/11/2025")),
                ("time", models.TimeField(default="00:00 AM")),
                ("price", models.IntegerField()),
                ("payment", models.CharField(max_length=20)),
                ("tyre_size", models.CharField(blank=True, max_length=55, null=True)),
                ("tyre_name", models.CharField(blank=True, max_length=55, null=True)),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
