# Generated by Django 5.2.8 on 2025-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billmodel",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
