# Generated by Django 5.2.8 on 2025-11-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("item_size", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("status", models.CharField(max_length=25)),
            ],
        ),
    ]
