# Generated by Django 5.2.8 on 2025-11-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="status",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
