# Generated by Django 5.2.8 on 2025-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventorymodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymodel",
            name="serial",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
